spring:
  application:
    name: doms-cnfg-srvc
  cloud:
    config:
      server:
        git:
          uri: https://github.com/idev4tek/doms-sttngs.git
          username: idev4tek
          password: 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
server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://144.217.155.167:8761/eureka/
  instance:
    hostname: localhost
